name: Lint Commits

on:
  push:
    branches:
      - "features/*"
      - "hotfix/*"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Fetch the base branch
        run: git fetch origin main:main
      - name: Lint commits
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            npx commitlint --from=origin/main
          else
            echo "Skipping commit linting because there are fewer than 2 commits."
          fi
