name: Lint Commits

on:
  push:
    branches:
      - "features/*"
      - "hotfix/*"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Verify Node.js version
        run: node -v 
      - name: Install dependencies
        run: npm install
      - name: Lint commits
        run: npx commitlint --from=HEAD~1
